-- Seed roles and users
-- NOTE: This file is for reference when using Flyway.
-- Currently, DataInitializer.java handles seeding automatically on application startup.
-- If you enable Flyway, you may need to update the BCrypt password hashes below.

-- Seed roles
INSERT INTO roles (name) VALUES ('ADMIN') ON DUPLICATE KEY UPDATE name=name;
INSERT INTO roles (name) VALUES ('USER') ON DUPLICATE KEY UPDATE name=name;

-- Seed users
-- Note: Passwords are BCrypt encoded (generated by PasswordEncoder)
-- Default credentials:
--   admin: admin123
--   user: user123
-- These hashes are examples - DataInitializer generates them dynamically
INSERT INTO users (username, email, password, enabled) 
VALUES ('admin', 'admin@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iwy8pK0e', true)
ON DUPLICATE KEY UPDATE username=username;

INSERT INTO users (username, email, password, enabled) 
VALUES ('user', 'user@example.com', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00kwN0YxJ5qK8q', true)
ON DUPLICATE KEY UPDATE username=username;

-- Assign roles to users
-- Admin user gets ADMIN role
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id 
FROM users u, roles r 
WHERE u.username = 'admin' AND r.name = 'ADMIN'
ON DUPLICATE KEY UPDATE user_id=user_id;

-- Regular user gets USER role
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id 
FROM users u, roles r 
WHERE u.username = 'user' AND r.name = 'USER'
ON DUPLICATE KEY UPDATE user_id=user_id;

